# Generated by Django 5.1.1 on 2024-09-14 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppGDP', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
