# Generated by Django 5.1.1 on 2024-09-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGDP', '0002_delete_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_inventario', models.CharField(max_length=10, unique=True)),
                ('denominacao', models.CharField(max_length=255)),
                ('localizacao', models.CharField(max_length=10)),
            ],
        ),
    ]
