# Generated by Django 5.1.1 on 2024-09-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGDP', '0003_inventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='link_imagem',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
